### ISSUE TITLE
Slack notification

### ISSUE THREAD

**Issue by ichiaohsu** [kwhsiung/mm-punch#3]
## Feature Request
**Is your feature request related to a problem? Please describe.**
When mm-punch failed to punch for members, we don't have access to know the situation until we actually login into the system. I think we could have better way to be informed of the failure.

**Describe the solution you'd like**
I think we could send error messages directly to slack we are using. It would be very convenient and effective.

I have dug into the slack sdk and found it's very simple. We could install `@slack/web-api`, put slack token in `.env`, init a slack client and call `chat.postMessage` then it's done.

**Describe alternatives you've considered**
Simply use log system, but I think it's in Heroku so it's not public basically.

**Teachability, Documentation, Adoption, Migration Strategy**
I may be able to help on this, but I think I need some documentation, or guidance for the error mechanism.

**Comment by kwhsiung** [comment]
Added by https://github.com/kwhsiung/mm-punch/commit/6151e963ac26621100c519d7b9848d29c7c9efb0

**Comment by ichiaohsu** [comment]
Use "close #3" in commit message will do the same thing :)
